Repository gmt-china/GMT_docs, pull requests merged in 2021-06, with the labels that each got.

#350 Add a note for DIR parameters
  source/conf/dir.rst
Labels: final review call

#355 Add data description for CN geospatial dataset
  source/dataset-CN/CN-border.rst
  source/dataset-CN/CN-faults.rst
Labels: final review call

#425 Fix the title underlines in ex011
  source/examples/ex011/index.rst
Labels: needs review

#430 Rename splitxyz to gmtsplit for GMT 6.2.0
  source/module/filter1d.rst
  source/module/index.rst
Labels: needs review

#429 Update CN province codes for DCW 2.0.0
  source/dataset/dcw/dcw-countries.txt
  source/dataset/dcw/dcw-states.txt
  source/dataset/dcw/index.rst
Labels: final review call

#427 Update CN faults
  source/dataset-CN/CN-faults.rst
Labels: final review call

#461 Fix the TOC of tutorials
  source/index.rst
  source/tutorial/advanced.rst
  source/tutorial/started.rst
Labels: needs review

#364 Add geo3al dataset
  source/dataset-CN/geo3al/geo3al.sh
  source/dataset-CN/geo3al/geoage.cpt
  source/dataset-CN/geo3al/index.rst
  source/dataset-CN/index.rst
Labels: final review call

#462 Add contributor information for geo3al
  source/conf.py
  source/dataset-CN/geo3al/index.rst
Labels: dataset

#464 Add learning guide on the landing page
  source/index.rst
Labels: maintenance

#473 Clarify when symbols or lines are ploted in plot module
  source/module/plot.rst
Labels: module
